global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
#  - job_name: "prometheus"
#    static_configs:
#      - targets: ["127.0.0.1:9090"]

  - job_name: "iaf-test"
    metrics_path: "/iaf-test/iaf/api/metrics/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: "iaf-example"
    metrics_path: "/iaf-example/iaf/api/metrics/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8080"]
