/*
 * $Log: HttpListener.java,v $
 * Revision 1.3  2007-10-03 08:37:49  europe\L190409
 * changed HashMap to Map
 *
 * Revision 1.2  2007/02/12 13:55:57  Gerrit van Brakel <gerrit.van.brakel@ibissource.org>
 * Logger from LogUtil
 *
 * Revision 1.1  2006/02/09 07:54:05  Gerrit van Brakel <gerrit.van.brakel@ibissource.org>
 * initial versions
 *
 */
package nl.nn.adapterframework.http;

import java.util.HashMap;
import java.util.Map;

import nl.nn.adapterframework.configuration.ConfigurationException;
import nl.nn.adapterframework.core.IMessageHandler;
import nl.nn.adapterframework.core.IPushingListener;
import nl.nn.adapterframework.core.IbisExceptionListener;
import nl.nn.adapterframework.core.ListenerException;
import nl.nn.adapterframework.core.PipeLineResult;
import nl.nn.adapterframework.receivers.ServiceClient2;
import nl.nn.adapterframework.receivers.ServiceDispatcher;
import nl.nn.adapterframework.util.LogUtil;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.log4j.Logger;

/**
 * Implementation of a {@link IPushingListener} that enables a {@link nl.nn.adapterframework.receivers.GenericReceiver}
 * to receive messages from HTTP requests.
 * <p><b>Configuration:</b>
 * <table border="1">
 * <tr><th>attributes</th><th>description</th><th>default</th></tr>
 * <tr><td>className</td><td>nl.nn.adapterframework.http.WebServiceListener</td><td>&nbsp;</td></tr>
 * <tr><td>{@link #setName(String) name}</td><td>name of the listener as known to the adapter</td><td>&nbsp;</td></tr>
 * <tr><td>{@link #setServiceName(String) serviceName}</td><td>name of the service that is provided by the adapter of this listener</td><td>&nbsp;</td></tr>
 * <tr><td>{@link #setApplicationFaultsAsExceptions(boolean) applicationFaultsAsExceptions}</td><td>Controls the behavior when an application-fault occurrs: 
 *   <table>
 *     <tr><td><code>true</code></td><td>errors are returned as a HTTP internal server error (500)</td></tr>
 *     <tr><td><code>false</code></td><td>errors are returned in error message generated by the IBIS error message formatter</td></tr>
 *   </table>
 * </td><td>true</td></tr>
 * </table>
 * @author  Gerrit van Brakel 
 * @since   4.4.x (still experimental)
 * @version Id
 */
public class HttpListener  implements IPushingListener, ServiceClient2 {
	public static final String version="$RCSfile: HttpListener.java,v $ $Revision: 1.3 $ $Date: 2007-10-03 08:37:49 $";
	protected Logger log = LogUtil.getLogger(this);

	private IMessageHandler handler;        	
	private String name;
	private String serviceName;
	private boolean applicationFaultsAsExceptions=false;

	/**
	 * initialize listener and register <code>this</code> to the JNDI
	 */
	public void configure() throws ConfigurationException {
		try {
			if (handler==null) {
				throw new ConfigurationException("handler has not been set");
			}
			if (StringUtils.isEmpty(getServiceName())) {
				log.debug("registering listener ["+getName()+"] with ServiceDispatcher");
				ServiceDispatcher.getInstance().registerServiceClient(getName(), this);
			} else {
				log.debug("registering listener ["+getName()+"] with ServiceDispatcher by serviceName ["+getServiceName()+"]");
				ServiceDispatcher.getInstance().registerServiceClient(getServiceName(), this);
			}
		} catch (Exception e){
			throw new ConfigurationException(e);
		}
	}

	public void open() {
		// do nothing special
	}
	public void close() {
		// do nothing special
	}


	public String getIdFromRawMessage(Object rawMessage, Map threadContext)  {
		return null;
	}
	public String getStringFromRawMessage(Object rawMessage, Map threadContext) {
		return (String) rawMessage;
	}
	public void afterMessageProcessed(PipeLineResult processResult, Object rawMessage, Map threadContext) throws ListenerException {
	}


	public String processRequest(String message) {
		try {
			return handler.processRequest(this, message);
		} catch (ListenerException e) {
			return handler.formatException(null,null, message,e);
		}
	}

	public String processRequest(String correlationId, String message) {
		try {
			log.debug("HttpListener processRequest for correlationId ["+correlationId+"]");
			return handler.processRequest(this, correlationId, message);
		} catch (ListenerException e) {
			return handler.formatException(null,correlationId, message,e);
		}
	}

	public String processRequestWithExceptions(String correlationId, String message, HashMap requestContext) throws ListenerException {
		try {
			log.debug("HttpListener processRequestWithExceptions for correlationId ["+correlationId+"]");
			return handler.processRequest(this, correlationId, message, requestContext);
		} catch (ListenerException e) {
			if (isApplicationFaultsAsExceptions()) {
				log.debug("processRequestWithExceptions rethrows ListenerException...");
				throw e;
			} 
			log.debug("processRequestWithExceptions formats ListenerException to errormessage");
			return handler.formatException(null,correlationId, message,e);
		}
	}


	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}

	/**
	 * Returns the name of the Listener. 
	 */
	public String getName() {
		return name;
	}
	/**
	 * Sets the name of the Listener. 
	 */
	public void setName(String name) {
		this.name=name;
	}

	public void setHandler(IMessageHandler handler) {
		this.handler=handler;
	}

	public void setExceptionListener(IbisExceptionListener listener) {
		// do nothing, no exceptions known
	}

	public String getServiceName() {
		return serviceName;
	}
	public void setServiceName(String string) {
		serviceName = string;
	}

	public boolean isApplicationFaultsAsExceptions() {
		return applicationFaultsAsExceptions;
	}
	public void setApplicationFaultsAsExceptions(boolean b) {
		applicationFaultsAsExceptions = b;
	}


}
