build = "mvn -Pibissource,codecoverage"
jdkVersion = "8"

disableTools = [ "golangci-lint" ]

ignoreFiles = """
**/js/angular/*.js
**/js/bootstrap/*.js
**/js/jquery/*.js
**/js/plugins/*.js
**/js/ui-router/*.js
"""
