
setup = ".lift/setup.sh"

build = "mvn install -P ibissource,codecoverage -DskipTests=true"
jdkVersion = "8"

disableTools = [ "golangci-lint", "JSHint", "Infer" ]

ignoreFiles = """
**/js/angular/*.js
**/js/bootstrap/*.js
**/js/jquery/*.js
**/js/plugins/*.js
**/js/ui-router/*.js
"""

tools = [ "ErrorProne" ]