packages:
  - 'console/frontend/src/main/frontend/'
  - 'console/frontend/src/main/frontend/cypress'
overrides:
  diff@>=6.0.0 <8.0.3: '~9.0.0'
  dompurify@<3.3.2: '~3.3.2'
  serialize-javascript@<7.0.5: '~7.0.5'
