/*
   Copyright 2013, 2019 Nationale-Nederlanden, 2022 WeAreFrank!

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.frankframework.scheduler;

import org.quartz.JobDataMap;
import org.quartz.JobExecutionContext;
import org.quartz.JobExecutionException;

import org.frankframework.core.PipeLineSession;
import org.frankframework.senders.IbisLocalSender;
import org.frankframework.stream.Message;

/**
 * Job, generated by SchedulerSender, for sending messages to a javalistener.
 * The <a href="http://quartz.sourceforge.net">Quartz scheduler</a> is used for scheduling.
 * <p>
 * Job is registered at runtime by the SchedulerSender
 *
 * @author John Dekker
 */
public class ServiceJob extends AbstractJob {

	public static final String JAVALISTENER_KEY = "javaListener";
	public static final String CORRELATIONID_KEY = "correlationId";
	public static final String MESSAGE_KEY = "message";

	public ServiceJob() {
		super();
	}

	@Override
	public void execute(JobExecutionContext context) throws JobExecutionException {
		log.info("executing {}", () -> getLogPrefix(context));
		JobDataMap dataMap = context.getJobDetail().getJobDataMap();
		String serviceName = dataMap.getString(JAVALISTENER_KEY);

		try (Message message = new Message(dataMap.getString(MESSAGE_KEY))) {
			// send job
			IbisLocalSender localSender = new IbisLocalSender();
			localSender.setJavaListener(serviceName);
			localSender.setIsolated(false);
			localSender.setName("ServiceJob");
			localSender.configure();

			localSender.start();
			try(PipeLineSession session = new PipeLineSession()) {
				localSender.sendMessageOrThrow(message, session).close();
			} finally {
				localSender.stop();
			}
		}
		catch (Exception e) {
			log.error("JobExecutionException while running {}", getLogPrefix(context), e);
			throw new JobExecutionException(e, false);
		}
		log.debug("{} completed", () -> getLogPrefix(context));
	}

}
