CREATE TABLE DATABASECHANGELOGLOCK (ID int NOT NULL, LOCKED bit NOT NULL, LOCKGRANTED datetime2(3), LOCKEDBY varchar(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))
GO
DELETE FROM DATABASECHANGELOGLOCK
GO
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, 0)
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = 'IGNORE', LOCKGRANTED = 'IGNORE' WHERE ID = 1 AND LOCKED = 0
GO
CREATE TABLE DATABASECHANGELOG (ID varchar(255) NOT NULL, AUTHOR varchar(255) NOT NULL, FILENAME varchar(255) NOT NULL, DATEEXECUTED datetime2(3) NOT NULL, ORDEREXECUTED int NOT NULL, EXECTYPE varchar(10) NOT NULL, MD5SUM varchar(35), DESCRIPTION varchar(255), COMMENTS varchar(255), TAG varchar(255), LIQUIBASE varchar(20), CONTEXTS varchar(255), LABELS varchar(255), DEPLOYMENT_ID varchar(10))
GO
USE testiaf;
GO
INSERT INTO DUMMYTABLE(TCHAR, TMESSAGE) VALUES ('C', 'MESSAGE');
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('insert row', 'Ali Sihab Akcan', 'Migrator/DatabaseChangelog_inserts.xml', GETDATE(), 1, 'CHANGESET-CHECKSUM', 'sql', '', 'EXECUTED', NULL, NULL, 'VERSION', 'IGNORE')
GO
CREATE TABLE DUMMYTABLE (TKEY bigint IDENTITY (1, 1) NOT NULL, TCHAR char(1), TMESSAGE varchar(100), CONSTRAINT PK_DUMMYTABLE PRIMARY KEY (TKEY));
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('one', 'Niels Meijer', 'Migrator/DatabaseChangelog_plus_changes.xml', GETDATE(), 2, 'CHANGESET-CHECKSUM', 'createTable tableName=DUMMYTABLE', 'Create DUMMYTABLE', 'EXECUTED', NULL, NULL, 'VERSION', 'IGNORE')
GO
DROP TABLE DUMMYTABLE;
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('two', 'Niels Meijer', 'Migrator/DatabaseChangelog_plus_changes.xml', GETDATE(), 3, 'CHANGESET-CHECKSUM', 'dropTable tableName=DUMMYTABLE', 'Drop DUMMYTABLE', 'EXECUTED', NULL, NULL, 'VERSION', 'IGNORE')
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID, TAG) VALUES ('three', 'Niels Meijer', 'Migrator/DatabaseChangelog_plus_changes.xml', GETDATE(), 4, 'CHANGESET-CHECKSUM', 'tagDatabase', '', 'EXECUTED', NULL, NULL, 'VERSION', 'IGNORE', 'tralala')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO
