UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = TRUE, LOCKEDBY = 'IGNORE', LOCKGRANTED = 'IGNORE' WHERE ID = 1 AND LOCKED = FALSE;

CREATE TABLE PUBLIC.DUMMYTABLE (TKEY BIGINT AUTO_INCREMENT NOT NULL, TCHAR CHAR(1), TMESSAGE VARCHAR(100), CONSTRAINT PK_DUMMYTABLE PRIMARY KEY (TKEY));

INSERT INTO PUBLIC.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('one', 'Niels Meijer', 'Migrator/DatabaseChangelog.xml', NOW(), 1, '8:6ea8506c569cc02162836312f364217f', 'createTable tableName=DUMMYTABLE', 'Create DUMMYTABLE', 'EXECUTED', NULL, NULL, '4.4.3', 'IGNORE');

DROP TABLE PUBLIC.DUMMYTABLE CASCADE;

INSERT INTO PUBLIC.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('two', 'Niels Meijer', 'Migrator/DatabaseChangelog.xml', NOW(), 2, '8:caa85ccb1dfe9e4b59561107126f4740', 'dropTable tableName=DUMMYTABLE', 'Drop DUMMYTABLE', 'EXECUTED', NULL, NULL, '4.4.3', 'IGNORE');

INSERT INTO PUBLIC.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID, TAG) VALUES ('three', 'Niels Meijer', 'Migrator/DatabaseChangelog.xml', NOW(), 3, '8:64ea2cfabf5f08738ffa2cfc5ee2f56a', 'tagDatabase', '', 'EXECUTED', NULL, NULL, '4.4.3', 'IGNORE', 'tralala');

UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;