CREATE TABLE DATABASECHANGELOGLOCK (ID int NOT NULL, LOCKED bit NOT NULL, LOCKGRANTED datetime2(3), LOCKEDBY nvarchar(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))
GO
DELETE FROM DATABASECHANGELOGLOCK
GO
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, 0)
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = 'IGNORE', LOCKGRANTED = 'IGNORE' WHERE ID = 1 AND LOCKED = 0
GO
CREATE TABLE DATABASECHANGELOG (ID nvarchar(255) NOT NULL, AUTHOR nvarchar(255) NOT NULL, FILENAME nvarchar(255) NOT NULL, DATEEXECUTED datetime2(3) NOT NULL, ORDEREXECUTED int NOT NULL, EXECTYPE nvarchar(10) NOT NULL, MD5SUM nvarchar(35), DESCRIPTION nvarchar(255), COMMENTS nvarchar(255), TAG nvarchar(255), LIQUIBASE nvarchar(20), CONTEXTS nvarchar(255), LABELS nvarchar(255), DEPLOYMENT_ID nvarchar(10))
GO
USE testiaf;
GO
INSERT INTO DUMMYTABLE(TCHAR, TMESSAGE) VALUES ('C', 'MESSAGE');
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('insert row', 'Ali Sihab Akcan', 'Migrator/DatabaseChangelog_inserts.xml', GETDATE(), 1, '9:a962170a7521bf01e3f381d81087ac55', 'sql', '', 'EXECUTED', NULL, NULL, 'VERSION', 'IGNORE')
GO
CREATE TABLE DUMMYTABLE (TKEY bigint IDENTITY (1, 1) NOT NULL, TCHAR char(1), TMESSAGE varchar(100), CONSTRAINT PK_DUMMYTABLE PRIMARY KEY (TKEY));
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('one', 'Niels Meijer', 'Migrator/DatabaseChangelog_plus_changes.xml', GETDATE(), 2, '9:77217a0fc5dc97422f45957a6ce88ab0', 'createTable tableName=DUMMYTABLE', 'Create DUMMYTABLE', 'EXECUTED', NULL, NULL, 'VERSION', 'IGNORE')
GO
DROP TABLE DUMMYTABLE;
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('two', 'Niels Meijer', 'Migrator/DatabaseChangelog_plus_changes.xml', GETDATE(), 3, '9:850b86b1bf7cba8ed747df4f928a8c22', 'dropTable tableName=DUMMYTABLE', 'Drop DUMMYTABLE', 'EXECUTED', NULL, NULL, 'VERSION', 'IGNORE')
GO
INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID, TAG) VALUES ('three', 'Niels Meijer', 'Migrator/DatabaseChangelog_plus_changes.xml', GETDATE(), 4, '9:f0f4b6b94a1eff02c5d6d1e0389ee437', 'tagDatabase', '', 'EXECUTED', NULL, NULL, 'VERSION', 'IGNORE', 'tralala')
GO
UPDATE DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
GO