name: Feature request
description: Request a new feature.
labels: ['Feature', 'Needs Triage']
body:
  - type: markdown
    attributes:
      value: |
        > [!CAUTION]
        > Please do not add sensitive information in issues, you can provide extra information via email using the issue number as reference.
  - type: textarea
    attributes:
      label: Related Problem or Business Case
      description: Please describe the related problem or why this feature should be added to the framework.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Feature
      description: Describe the solution you'd like.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Collaboration with External Companies
      description: Are you open to having external companies solve this issue or create an impact analysis for payment?
      multiple: false
      options:
        - Yes, solve the problem
        - Yes, create impact analysis
        - No, community resolution only
      default: 2
    validations:
      required: false
  - type: textarea 
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        > [!TIP]
        > You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
