name: Epic
description: Define a body of work that can be broken down into specific tasks.
labels: ['Needs Triage']
type: Epic
projects: ['frankframework/2']
body:
  - type: markdown
    attributes:
      value: |
        > [!CAUTION]
        > Please do not add sensitive information in issues, you can provide extra information via email using the issue number as reference.
  - type: textarea
    attributes:
      label: Goal
      description: Describe the problem or opportunity.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Detailed explanation how we can meet/implement the before mentioned goal.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Tasks
      description: Define a list of specific tasks.
      placeholder: |
        - [ ] Task #1
        - [ ] Task #2
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        > [!TIP]
        > You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
