blank_issues_enabled: false
contact_links:
  - name: Frank!Framework Community Support
    url: https://github.com/frankframework/frankframework/discussions
    about: Please ask and answer questions here.
