version: ''

services:
  ff-test:
    environment:
      jms.provider.default: activemq
      jms.destination.suffix: -activemq
      jms.hostname: activemq
      active.amqp: true

  activemq:
    image: ghcr.io/frankframework/mq/activemq
    ports:
      - "5672:5672"
      - "61616:61616"
      - "8161:8161"
