version: '3.8'

services:
    ff-test:
        environment:
            jms.provider.default: artemis
            jms.destination.suffix: -artemis
            jms.hostname: artemis

    artemis:
        image: private.docker.nexus.frankframework.org/ff-test/mq/artemis
        ports:
            - "61615:61615"
