version: ''

services:
  ff-test:
    environment:
      jdbc.dbms.default: db2-xa
      jdbc.hostname: db2
      jdbc.migrator.datasource: jdbc/ibis4test-db2
      active.storedProcedureTests: true

  db2:
    image: ghcr.io/frankframework/dbms/db2
    privileged: true
    ports:
      - "50000:50000"
