version: ''

name: jboss

services:
  ff-test:
    volumes:
      - ../test/src/test/testtool:/opt/frank/testtool-ext
    image: private.docker.nexus.frankframework.org/ff-test:${VERSION:-latest}-jboss
    build: JBoss
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      larva.adapter.active: false
    restart: unless-stopped
