version: ''

services:
  ff-test:
    environment:
      jdbc.dbms.default: mssql
      jdbc.hostname: mssql
      active.storedProcedureTests: true

  mssql:
    image: ghcr.io/frankframework/dbms/mssqlserver
    ports:
      - "1433:1433"
