version: ''

services:
  ff-test:
    environment:
      jdbc.dbms.default: mysql
      jdbc.hostname: mysql
      active.storedProcedureTests: true

  mysql:
    image: ghcr.io/frankframework/dbms/mysql
    ports:
      - "3307:3307"
