version: ''

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs/:/etc/nginx/certs/
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
