version: ''

services:
  ff-test:
    environment:
      jdbc.dbms.default: oracle
      jdbc.hostname: oracle

  oracle:
    image: private.docker.nexus.frankframework.org/ff-test/dbms/oracle
    ports:
      - "1521:1521"
