version: ''

services:
  ff-test:
    environment:
      jdbc.dbms.default: postgres
      jdbc.hostname: postgres
      active.storedProcedureTests: true

  postgres:
    image: ghcr.io/frankframework/dbms/postgresql
    ports:
      - "5432:5432"
