version: '3.8'

services:
    ff-test:
        volumes:
            - ../test/src/test/testtool:/opt/frank/testtool-ext
        image: private.docker.nexus.frankframework.org/ff-test:${VERSION:-latest}-tomcat
        build: Tomcat/test
        ports:
            - "80:8080"
        environment:
            application.server.type.custom: NARAYANA
            larva.adapter.active: false
