import './app/app.component';

// import './app/views/configurations/configurations-manage/configurations-manage.component';
// import './app/views/configurations/configurations-manage/configurations-manage-details/configurations-manage-details.component';
// import './app/views/configurations/configurations-show/configurations-show.component';
// import './app/views/configurations/configurations-upload/configurations-upload.component';
// import './app/views/iaf-update/iaf-update-status.component';
// import './app/views/connections/connections.component';
// import './app/views/error/error.component';
// import './app/views/liquibase/liquibase.component';
// import './app/views/loading/loading.component';
import './app/views/login/login.component';
// import './app/views/logging/logging.component';
// import './app/views/logging/logging-manage/logging-manage.component';
// import './app/views/monitors/monitors-add-edit/monitors-add-edit.component';
// import './app/views/monitors/monitors.component';
// import './app/views/notifications/notifications.component';
// import './app/views/scheduler/scheduler.component';
// import './app/views/scheduler/scheduler-add/scheduler-add.component';
// import './app/views/scheduler/scheduler-edit/scheduler-edit.component';
// import './app/views/security-items/security-items.component';
// import './app/views/status/status.component';
// import './app/views/status/flow/flow.component';
// import './app/views/status/flow/flow-modal/flow-modal.component';
// import './app/views/storage/storage.component';
// import './app/views/test-pipeline/test-pipeline.component';
// import './app/views/test-service-listener/test-service-listener.component';
// import './app/views/webservices/webservices.component';
