/*
   Copyright 2018-2020 Nationale-Nederlanden, 2020-2024 WeAreFrank!

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.frankframework.ibistesttool.larva;

import nl.nn.testtool.Checkpoint;
import nl.nn.testtool.Report;
import nl.nn.testtool.extensions.CustomReportAction;
import nl.nn.testtool.extensions.CustomReportActionResult;

import nu.studer.java.util.OrderedProperties;

import java.io.File;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.OptionalInt;
import java.util.stream.Stream;

public class ConvertToLarvaAction implements CustomReportAction {

	private Path dir;

	@Override
	public String getButtonText() {
		return "Convert to Larva";
	}

	public void setReportsFolder(String dir) {
		this.dir = Paths.get(dir, "autogenerated");
	}

	@Override
	public CustomReportActionResult handleReports(List<Report> reports) {
		List<Report> successReports = new ArrayList<>();
		CustomReportActionResult customReportActionResult = new CustomReportActionResult();
		StringBuilder additionalErrors = new StringBuilder();

		for (Report report : reports) {
			List<Map<Path, String>> originalResources = new ArrayList<>();
			List<Path> newResources = new ArrayList<>();
			String reportName = report.getName();
			if (!checkReportType(customReportActionResult, reportName)) continue;

			String adapterName = reportName.substring(9);
			Path testDir = dir.resolve(adapterName);
			if (!tryCreateDir(customReportActionResult, reportName, testDir)) continue;

			String scenarioSuffix = tryGetScenarioSuffix(customReportActionResult, reportName, testDir);
			if (scenarioSuffix.isEmpty()) continue;

			Path scenarioDir = testDir.resolve(scenarioSuffix);
			Path scenarioFile = testDir.resolve("scenario" + scenarioSuffix + ".properties");
			Path commonFile = testDir.resolve("common.properties");
			if (!checkScenarioDirNotInUse(customReportActionResult, reportName, scenarioDir)) continue;
			if (!tryCreateCommonFile(customReportActionResult, reportName, commonFile)) continue;

			// Create scenario with the properties resolved earlier
			Scenario scenario = new Scenario(report, scenarioDir, scenarioFile, commonFile, adapterName);
			// If creating the scenario created additional errors, add them to the list of additional errors
			if (!scenario.errors.isEmpty()) {
				additionalErrors.append("\t[").append(report).append("]: ").append(String.join("\r\n", scenario.errors));
			}
			successReports.add(report);
		}

		//If there are additional errors, append them to the existing error message
		if (additionalErrors.length() != 0) {
			String oldError = customReportActionResult.getErrorMessage();
			customReportActionResult.setErrorMessage(
					(oldError != null && !oldError.isEmpty() ? oldError + "\r\n" : "") +
							"Errors while generating test scenarios: \r\n" +
							additionalErrors
			);
		}
		customReportActionResult.setSuccessMessage("Generated larva test scenario(s) for reports: " + successReports);
		return customReportActionResult;
	}

	private boolean checkReportType(CustomReportActionResult customReportActionResult, String reportName) {
		if (!reportName.startsWith("Pipeline ")) {
			addErrorToResult(customReportActionResult, reportName, "This not a pipeline report. Test generation isn't implemented for this type of report.");
			return false;
		}
		return true;
	}

	private boolean tryCreateDir(CustomReportActionResult customReportActionResult, String reportName, Path testDir) {
		try {
			// Tries to create dir and parents. Does not throw error if it already exists
			Files.createDirectories(testDir);
		} catch (IOException e) {
			addErrorToResult(customReportActionResult, reportName, "Could not create test directory [" + testDir.toAbsolutePath().normalize() + "]");
			return false;
		}
		return true;
	}

	private String tryGetScenarioSuffix(CustomReportActionResult customReportActionResult, String reportName, Path testDir) {
		String scenarioSuffix = "";
		try (Stream<Path> list = Files.list(testDir)) {
			//Get the highest suffix found in the directory, both in file and directory names
			OptionalInt maxSuffix = list.mapToInt(path -> {
				String fileName = path.getFileName().toString();
				if (Files.isDirectory(path)) {
					if (fileName.matches("\\d+")) {
						return Integer.parseInt(fileName);
					}
				} else if (fileName.matches("scenario\\d+.properties")) {
					return Integer.parseInt(fileName.substring(8,fileName.indexOf(".")));
				}
				return -1;
			}).max();
			if (maxSuffix.isPresent()) {
				scenarioSuffix = String.format("%0" + 2 + "d", maxSuffix.getAsInt() + 1);
			} else {
				scenarioSuffix = "01";
			}
		} catch (IOException e) {
			addErrorToResult(customReportActionResult, reportName, "Could not count existing scenarios in test directory [" + testDir.toAbsolutePath().normalize() + "]");
		}
		return scenarioSuffix;
	}

	private boolean checkScenarioDirNotInUse(CustomReportActionResult customReportActionResult, String reportName, Path scenarioDir) {
		if (!Files.exists(scenarioDir)) {
			try {
				Files.createDirectory(scenarioDir);
			} catch (IOException e) {
				addErrorToResult(customReportActionResult, reportName, "Could not create scenario directory [" + scenarioDir.toAbsolutePath().normalize() + "]");
				return false;
			}
		} else {
			try(Stream<Path> files = Files.list(scenarioDir)) {
				if (files.findAny().isPresent()) {
					addErrorToResult(customReportActionResult, reportName, "Scenario directory [" + scenarioDir.toAbsolutePath().normalize() + "] already exists and is not empty");
					return false;
				}
			} catch (IOException e) {
				addErrorToResult(customReportActionResult, reportName, "Scenario directory [" + scenarioDir.toAbsolutePath().normalize() + "] already exists and could not be checked for files inside of it");
				return false;
			}
		}
		return true;
	}

	private boolean tryCreateCommonFile(CustomReportActionResult customReportActionResult, String reportName, Path commonFile) {
		if (!Files.exists(commonFile)) {
			try {
				Files.createFile(commonFile);
			} catch (IOException e) {
				addErrorToResult(customReportActionResult, reportName, "Could not create common file [" + commonFile.toAbsolutePath().normalize() + "]");
				return false;
			}
		}
		return true;
	}

	private void addErrorToResult(CustomReportActionResult customReportActionResult, String reportName, String reason) {
		String oldError = customReportActionResult.getErrorMessage();
		customReportActionResult.setErrorMessage(
				(oldError != null && !oldError.isEmpty() ? oldError : "Following reports could not be converted:") +
						"\r\n\t[" + reportName + "]: " + reason
		);
	}

	public static String stepPadding(int i) {
		return String.format("%0" + 2 + "d", i);
	}

	private static class Scenario {


		private static final HashSet<String> allowedSenders = new HashSet<>(Arrays.asList(
				"org.frankframework.senders.DelaySender",
				"org.frankframework.senders.EchoSender",
				"org.frankframework.senders.IbisLocalSender",
				"org.frankframework.senders.LogSender",
				"org.frankframework.senders.ParallelSenders",
				"org.frankframework.senders.SenderSeries",
				"org.frankframework.senders.SenderWrapper",
				"org.frankframework.senders.XsltSender",
				"org.frankframework.senders.CommandSender",
				"org.frankframework.senders.FixedResultSender",
				"org.frankframework.senders.JavascriptSender",
				"org.frankframework.jdbc.MessageStoreSender",
				"org.frankframework.senders.ReloadSender",
				"org.frankframework.compression.ZipWriterSender"
		));

		private static final HashSet<String> ignoredSessionKeys = new HashSet<>(Arrays.asList(
				"cid",
				"mid",
				"id",
				"key",
				"messageId",
				"originalMessage",
				"tcid",
				"tsReceived",
				"conversationId",
				"timestamp",
				"tsSent",
				"xPathLogKeys",
				"replyTo",
				"JmsSession",
				"servletResponse",
				"servletRequest",
				"servletContext",
				"securityHandler",
				"__isManualRetry"
		));

		public List<String> errors = new ArrayList<>();

		public Scenario(Report report, Path scenarioDir, Path scenario, Path common, String adapterName) {
			Map<String, String> existingStubs = new HashMap<>();

			String scenarioDirPrefix = scenarioDir.getFileName().toString() + "/";
			File scenarioFile = scenario.toFile();
			File commonFile = common.toFile();

			OrderedProperties.OrderedPropertiesBuilder commonBuilder = new OrderedProperties.OrderedPropertiesBuilder();
			commonBuilder.withOrdering(new CommonPropertiesComparator());
			commonBuilder.withSuppressDateInComment(true);
			OrderedProperties commonProperties = commonBuilder.build();

			OrderedProperties.OrderedPropertiesBuilder scenarioBuilder = new OrderedProperties.OrderedPropertiesBuilder();
			scenarioBuilder.withOrdering(new ScenarioPropertiesComparator());
			scenarioBuilder.withSuppressDateInComment(true);
			OrderedProperties scenarioProperties = scenarioBuilder.build();

			scenarioProperties.setProperty("scenario.description", "Test scenario for adapter " + adapterName + ", automatically generated based on a ladybug report");
			scenarioProperties.setProperty("include", "common.properties");
			String adapterProperty = "adapter." + adapterName.replaceAll("\\s","-");
			int paramI = 1;
			int current_step_nr = 0;
			List<Checkpoint> checkpoints = report.getCheckpoints();
			scenarioProperties.setProperty("step" + ++current_step_nr + "." + adapterProperty + ".write", scenarioDirPrefix + stepPadding(current_step_nr) + "-adapter-" + adapterName + "-in.xml");
			createInputOutputFile(scenarioDir, current_step_nr, "adapter", adapterName, true, checkpoints.get(0).getMessage());
			commonProperties.setProperty(adapterProperty + ".className", "org.frankframework.senders.IbisJavaSender");
			commonProperties.setProperty(adapterProperty + ".serviceName", "testtool-" + adapterName);
			commonProperties.setProperty(adapterProperty + ".convertExceptionToMessage", "true");

			boolean skipUntilEndOfSender = false;
			String skipUntilEndOfSenderName = "";
			int skipUntilEndOfSenderLevel = -1;

			for (Checkpoint checkpoint : checkpoints) {
				if (skipUntilEndOfSender) {
					//If we're currently stubbing a sender, and we haven't reached the end of it yet
					String checkpointName = checkpoint.getName().substring(7);
					if (checkpoint.getLevel() == skipUntilEndOfSenderLevel && checkpoint.getType() == Checkpoint.TYPE_ENDPOINT && checkpointName.equals(skipUntilEndOfSenderName)) {
						createInputOutputFile(scenarioDir, current_step_nr, "stub", checkpointName, false, checkpoint.getMessage());
						skipUntilEndOfSender = false;
					}
				} else if (checkpoint.getType() == Checkpoint.TYPE_STARTPOINT && checkpoint.getName().startsWith("Sender ")) {
					if (!allowedSenders.contains(checkpoint.getSourceClassName())) {
						//If sender should be stubbed:
						String senderName = checkpoint.getName().substring(7, checkpoint.getName().length() - 7);
						String senderProperty = "stub." + senderName.replaceAll("\\s","-");
						scenarioProperties.setProperty("step" + ++current_step_nr + "." + senderProperty + ".read", scenarioDirPrefix + stepPadding(current_step_nr) + "-stub-" + senderName + "-in.xml");
						createInputOutputFile(scenarioDir, current_step_nr, "stub", senderName, true, checkpoint.getMessage());
						scenarioProperties.setProperty("step" + ++current_step_nr + "." + senderProperty + ".write", scenarioDirPrefix + stepPadding(current_step_nr) + "-stub-" + senderName + "-out.xml");

						String serviceName = "testtool-" + senderName;
						String existingStubName = existingStubs.get(serviceName.toLowerCase());
						if (!senderProperty.equals(existingStubName)) {
							existingStubs.put(serviceName.toLowerCase(), senderProperty);
							commonProperties.setProperty(senderProperty + ".className", "org.frankframework.receivers.JavaListener");
							commonProperties.setProperty(senderProperty + ".serviceName", serviceName);

							if (existingStubName != null) {
								commonProperties.removeProperty(existingStubName + ".className");
								commonProperties.removeProperty(existingStubName + ".serviceName");
								try {
									replaceStubName(scenario.getParent(), existingStubName, senderProperty);
								} catch (IOException e) {
									errors.add("Could not replace old stub name [" + existingStubName + "] with new stub name [" + senderProperty + "]");
								}
							}
						}

						skipUntilEndOfSender = true;
						skipUntilEndOfSenderName = senderName;
						skipUntilEndOfSenderLevel = checkpoint.getLevel() + 1;
					}
				} else if (checkpoint.getLevel() == 1 && checkpoint.getType() == Checkpoint.TYPE_INPUTPOINT && checkpoint.getName().startsWith("SessionKey ")) {
					//SessionKey for listener found
					String sessionKeyName = checkpoint.getName().substring(11);
					if (!ignoredSessionKeys.contains(sessionKeyName)) {
						scenarioProperties.setProperty(adapterProperty + ".param" + paramI + ".name", sessionKeyName);
						scenarioProperties.setProperty(adapterProperty + ".param" + paramI + ".value", checkpoint.getMessage());
						paramI++;
					}
				}
			}
			scenarioProperties.setProperty("step" + ++current_step_nr + "." + adapterProperty + ".read", scenarioDirPrefix + stepPadding(current_step_nr) + "-adapter-" + adapterName + "-out.xml");
			createInputOutputFile(scenarioDir, current_step_nr, "adapter", adapterName, false, checkpoints.get(checkpoints.size() - 1).getMessage());

			try (OutputStreamWriter scenarioWriter = new OutputStreamWriter(Files.newOutputStream(scenarioFile.toPath()), StandardCharsets.UTF_8);) {
				scenarioProperties.store(scenarioWriter, null);
			} catch (IOException e) {
				errors.add("Could not write properties to file [" + scenarioFile + "]");
			}
			try (OutputStreamWriter commonWriter = new OutputStreamWriter(Files.newOutputStream(commonFile.toPath()), StandardCharsets.UTF_8)) {
				commonProperties.store(commonWriter, null);
			} catch (IOException e) {
				errors.add("Could not write properties to file [" + commonFile + "]");
			}
		}

		private static void replaceStubName(Path folder, String oldStubName, String newStubName) throws IOException {
			if (oldStubName.equals(newStubName)) {
				return;
			}
			File[] scenarios = folder.toFile().listFiles((dir, name) -> name.matches("scenario\\d*\\.properties"));
			assert scenarios != null;
			for (File scenario : scenarios) {
				List<String> result = Files.readAllLines(scenario.toPath());
				boolean changed = false;
				for (int i = 0; i < result.size(); i++) {
					String line = result.get(i);
					if (line.contains(oldStubName + ".read") || line.contains(oldStubName + ".write")) {
						result.set(i, line.replace(oldStubName, newStubName));
						changed = true;
					}
				}
				if (changed) Files.write(scenario.toPath(), result);
			}
		}

		private void createInputOutputFile(Path folder, int step, String type, String name, boolean startpoint, String message) {
			String filename = String.format("%s-%s-%s-%s.xml", stepPadding(step), type, name, startpoint ? "in" : "out");
			File messageFile = folder.resolve(filename).toFile();
			try {
				if (messageFile.createNewFile()) {
					Files.writeString(messageFile.toPath(), message);
				}
			} catch (IOException e) {
				errors.add("Could not create message file: [" + messageFile + "]");
			}
		}
	}

}
