/*
   Copyright 2025-2026 WeAreFrank!

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.frankframework.errormessageformatters;

import java.io.IOException;
import java.util.Map;
import java.util.stream.Collectors;

import org.apache.commons.lang3.StringUtils;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

import com.datasonnet.Mapper;
import com.datasonnet.MapperBuilder;

import org.frankframework.configuration.ConfigurationException;
import org.frankframework.configuration.ConfigurationWarning;
import org.frankframework.core.HasName;
import org.frankframework.core.IConfigurable;
import org.frankframework.core.IErrorMessageFormatter;
import org.frankframework.core.IScopeProvider;
import org.frankframework.core.IWithParameters;
import org.frankframework.core.ParameterException;
import org.frankframework.core.PipeLineSession;
import org.frankframework.doc.Mandatory;
import org.frankframework.doc.Protected;
import org.frankframework.documentbuilder.DocumentFormat;
import org.frankframework.functional.FunctionalUtil;
import org.frankframework.json.DataSonnetOutputType;
import org.frankframework.json.DataSonnetUtil;
import org.frankframework.parameters.IParameter;
import org.frankframework.parameters.ParameterList;
import org.frankframework.stream.Message;
import org.frankframework.util.Misc;
import org.frankframework.util.StringUtil;

/**
 * Applies a DataSonnet {@code .jsonnet} JSON transformation file to the standard JSON error message generated by the {@link ErrorMessageFormatter}.
 *
 * <p>
 *     If the transformation does not succeed, this 'standard' error message is returned in JSON format and an exception is logged.
 * </p>
 *
 * @ff.parameters All parameters are added to the {@code .jsonnet} stylesheet. Parameter names must be unique.
 *
 * @since 9.2
 *
 * @see IErrorMessageFormatter for general information on error message formatters.
 * @see <a href="https://jsonnet.org/">https://jsonnet.org/</a> for live examples of `.jsonnet` files.
 * @see <a href="https://datasonnet.github.io/datasonnet-mapper/datasonnet/latest/cookbook.html">DataSonnet cookbook</a>.
 */
@NullMarked
public class DataSonnetErrorMessageFormatter extends ErrorMessageFormatter implements IErrorMessageFormatter, IConfigurable, IScopeProvider, IWithParameters {

	@SuppressWarnings({ "NullAway.Init", "java:S2637" })
	private String styleSheetName;
	private DataSonnetOutputType outputType = DataSonnetOutputType.JSON;
	@SuppressWarnings({ "NullAway.Init", "java:S2637" })
	private Mapper mapper;
	private final ParameterList parameters = new ParameterList();
	private @Nullable String imports;

	@Override
	public void configure() throws ConfigurationException {
		super.setMessageFormat(DocumentFormat.JSON);
		if (StringUtils.isBlank(styleSheetName)) {
			throw new ConfigurationException("DataSonnet transformation stylesheet not set");
		}

		parameters.setNamesMustBeUnique(true);
		parameters.configure();

		Map<String, String> importMap = StringUtil.splitToStream(imports, ",;")
				.collect(Collectors.toMap(n -> n, n -> FunctionalUtil.throwingLambda(() -> Misc.getStyleSheet(this, n))));
		mapper = new MapperBuilder(Misc.getStyleSheet(this, styleSheetName))
				.withImports(importMap)
				.withInputNames(getParameterList().getParameterNames())
				.build();
	}

	@Override
	public Message format(@Nullable String errorMessage, @Nullable Throwable t, @Nullable HasName location, @Nullable Message originalMessage, PipeLineSession session) {
		try {
			Message defaultMessage = super.format(errorMessage, t, location, originalMessage, session);
			return DataSonnetUtil.transform(mapper, defaultMessage, parameters.getValues(originalMessage, session), outputType);
		} catch (IOException e) {
			throw new FormatterException("Cannot format error message", e);
		} catch (ParameterException e) {
			throw new FormatterException("Cannot extract parameter values", e);
		} catch (RuntimeException e) {
			throw new FormatterException("Cannot apply DataSonnet transformation to default JSON error message", e);
		}
	}

	/**
	 * Set a DataSonnet stylesheet to transform the default JSON error message to a custom format.
	 */
	@Mandatory
	public void setStyleSheetName(String styleSheetName) {
		this.styleSheetName = styleSheetName;
	}

	/**
	 * Output file format. DataSonnet is semi-capable of converting the converted JSON to a different format.
	 *
	 * @ff.default JSON
	 */
	public void setOutputFileFormat(DataSonnetOutputType outputType) {
		this.outputType = outputType;
	}

	@Deprecated
	@ConfigurationWarning("for documentation purposes we've renamed this field to [outputFileFormat]")
	public void setOutputType(DataSonnetOutputType outputType) {
		setOutputFileFormat(outputType);
	}

	@Override
	@Protected
	public void setMessageFormat(DocumentFormat messageFormat) {
		throw new UnsupportedOperationException("Not supported for this type");
	}

	@Override
	public void addParameter(IParameter p) {
		parameters.add(p);
	}

	@Override
	public ParameterList getParameterList() {
		return parameters;
	}

	/**
	 * List of stylesheets / DataSonnet files imported by the stylesheet to be executed. Stylesheets are only evaluated as JSonnet files if the filename has the extension {@literal .ds} or {@literal .libsonnet}.
	 *
	 * <p>
	 *     The list of stylesheets is expected to be a comma-separated list of files, which are loaded from the configuration.
	 *     Import statements in DataSonnet cannot be used unless each file to be imported is listed here in the {@code imports} attribute.
	 * </p>
	 * <p>
	 *     Imported files may not be able to use DataSonnet functions from DataSonnet's own libraries, normally available as {@code ds.map()} and the like. The
	 *     cause for this is not yet known.
	 * </p>
	 */
	public void setImports(String imports) {
		this.imports = imports;
	}
}
