/*
   Copyright 2013, 2018 Nationale-Nederlanden, 2020-2025 WeAreFrank!

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.frankframework.errormessageformatters;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

import org.apache.commons.lang3.StringUtils;

import lombok.Getter;
import lombok.extern.log4j.Log4j2;

import org.frankframework.configuration.ConfigurationException;
import org.frankframework.configuration.ConfigurationWarning;
import org.frankframework.core.HasName;
import org.frankframework.core.IConfigurable;
import org.frankframework.core.IWithParameters;
import org.frankframework.core.ParameterException;
import org.frankframework.core.PipeLineSession;
import org.frankframework.core.Resource;
import org.frankframework.doc.Protected;
import org.frankframework.documentbuilder.DocumentFormat;
import org.frankframework.parameters.IParameter;
import org.frankframework.parameters.ParameterList;
import org.frankframework.parameters.ParameterValueList;
import org.frankframework.stream.Message;
import org.frankframework.util.TransformerPool;
import org.frankframework.util.TransformerPool.OutputType;

/**
 * Applies an XSLT-stylesheet to the standard error generated by an {@link ErrorMessageFormatter}.
 *
 * If the transformation does not succeed, this 'standard' error message is returned and an exception is logged.
 * <br/>
 * @ff.tip use <code>xpathExpression="/errorMessage/@message"</code> for a single compact string as errormessage.
 *
 * @author Johan Verrips IOS
 */
@Log4j2
public class XslErrorMessageFormatter extends ErrorMessageFormatter implements IWithParameters, IConfigurable {

	protected @Nonnull ParameterList paramList = new ParameterList();

	private @Getter String styleSheetName;
	private @Getter String xpathExpression;

	private TransformerPool transformerPool;

	@Override
	public void configure() throws ConfigurationException {
		super.setMessageFormat(DocumentFormat.XML);
		paramList.setNamesMustBeUnique(true);
		paramList.configure();

		if (StringUtils.isNotEmpty(getStyleSheetName())) {
			try {
				Resource xsltSource = Resource.getResource(this, getStyleSheetName());
				transformerPool = TransformerPool.getInstance(xsltSource, 0);
			} catch (Exception e) {
				throw new ConfigurationException("Cannot configure stylesheet transformer for [" + styleSheetName + "]", e);
			}
		} else {
			try {
				transformerPool = TransformerPool.getXPathTransformerPool(null, getXpathExpression(), OutputType.TEXT, false, getParameterList());
			} catch (Exception e) {
				throw new ConfigurationException("Cannot configure XPath transformer for [" + xpathExpression + "]", e);
			}
		}
	}

	@Override
	public Message format(String errorMessage, Throwable t, HasName location, Message originalMessage, PipeLineSession session) {

		Message result = super.format(errorMessage, t, location, originalMessage, session);

		if (!StringUtils.isNotEmpty(getStyleSheetName()) && !StringUtils.isNotEmpty(getXpathExpression())) {
			log.warn("no stylesheet or xpathExpression defined for XslErrorMessageFormatter");
			return result;
		}
		try {
			ParameterValueList parameterValueList = getParameterValues(errorMessage, session);
			try (Message closeable = result) {
				return transformerPool.transform(closeable, parameterValueList);
			}
		} catch (Exception tfe) {
			log.error("could not transform [{}] using stylesheet [{}]", result, getStyleSheetName(), tfe);
		}
		return result;
	}

	@Nullable
	private ParameterValueList getParameterValues(String errorMessage, PipeLineSession session) {
		try {
			return getParameterList().getValues(new Message(errorMessage), session);
		} catch (ParameterException e) {
			log.error("got exception extracting parameters", e);
		}
		return null;
	}

	@Override
	public void addParameter(IParameter p) {
		paramList.add(p);
	}

	@Override
	public @Nonnull ParameterList getParameterList() {
		return paramList;
	}

	/**
	 * URL to the stylesheet used to transform the output of the standard {@link ErrorMessageFormatter}
	 *
	 * @deprecated Use {@link #setStyleSheetName(String)} instead
	 */
	@Deprecated
	@ConfigurationWarning("Use attribute [styleSheetName] instead")
	public void setStyleSheet(String newStyleSheet) {
		styleSheetName = newStyleSheet;
	}

	/**
	 * URL to the stylesheet used to transform the output of the standard {@link ErrorMessageFormatter}
	 */
	public void setStyleSheetName(String styleSheetName) {
		this.styleSheetName = styleSheetName;
	}

	/** xPathExpression to use for transformation */
	public void setXpathExpression(String string) {
		xpathExpression = string;
	}

	@Override
	@Protected
	public void setMessageFormat(@Nonnull DocumentFormat messageFormat) {
		throw new UnsupportedOperationException("Not supported for this type");
	}
}
