<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<wsdl:definitions
	xmlns:BG="http://www.egem.nl/StUF/sector/bg/0310"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<schema>
			<import namespace="http://www.egem.nl/StUF/sector/bg/0310"
				schemaLocation="types.xsd" />
		</schema>
	</wsdl:types>
	<wsdl:message name="npsLv01">
		<wsdl:part name="body" element="BG:npsLv01" />
	</wsdl:message>

</wsdl:definitions>
