---------------------------------------------------
--   CREATE TABLE IBISPROP
---------------------------------------------------

CREATE TABLE IBISPROP
(
  NAME VARCHAR2(100 CHAR) NOT NULL,
  VALUE VARCHAR2(100 CHAR),
  LASTMODDATE TIMESTAMP(6),
  LASTMODBY VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX PK_IBISPROP ON IBISPROP
(NAME)
LOGGING
NOPARALLEL;


ALTER TABLE IBISPROP ADD (
  CONSTRAINT PK_IBISPROP
 PRIMARY KEY
 (NAME));

---------------------------------------------------
--   CREATE TABLE IBISSTORE
---------------------------------------------------

CREATE TABLE IBISSTORE
(
  MESSAGEKEY     NUMBER(10),
  TYPE           CHAR(1 CHAR),
  SLOTID         VARCHAR2(100 CHAR),
  HOST           VARCHAR2(100 CHAR),
  MESSAGEID      VARCHAR2(100 CHAR),
  CORRELATIONID  VARCHAR2(256 CHAR),
  MESSAGEDATE    TIMESTAMP(6),
  COMMENTS       VARCHAR2(1000 CHAR),
  MESSAGE        BLOB,
  EXPIRYDATE     TIMESTAMP(6),
  LABEL          VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX PK_IBISSTORE ON IBISSTORE
(MESSAGEKEY)
LOGGING
NOPARALLEL;


CREATE INDEX IX_IBISSTORE ON IBISSTORE
(TYPE, SLOTID, MESSAGEDATE)
LOGGING
NOPARALLEL;


CREATE INDEX IX_IBISSTORE_02 ON IBISSTORE
(EXPIRYDATE)
LOGGING
NOPARALLEL;


ALTER TABLE IBISSTORE ADD (
  CONSTRAINT PK_IBISSTORE
 PRIMARY KEY
 (MESSAGEKEY));

---------------------------------------------------
--   CREATE TABLE IBISDATA
---------------------------------------------------

CREATE TABLE IBISDATA
(
  DATAKEY NUMBER(10, 0) NOT NULL,
  DATA BLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX PK_IBISDATA ON IBISDATA
(DATAKEY)
LOGGING
NOPARALLEL;


ALTER TABLE IBISDATA ADD (
  CONSTRAINT PK_IBISDATA
 PRIMARY KEY
 (DATAKEY));

---------------------------------------------------
--   CREATE TABLE IBISTEMP
---------------------------------------------------

CREATE TABLE IBISTEMP
(
  TKEY           NUMBER(10),
  TCHAR          CHAR(1 CHAR),
  TVARCHAR       VARCHAR2(100 CHAR),
  TNUMBER        NUMBER(17, 5),
  TTIMESTAMP     TIMESTAMP,
  TDATE          DATE,
  TBLOB1         BLOB,
  TCLOB          CLOB,
  TBLOB2         BLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX PK_IBISTEMP ON IBISTEMP
(TKEY)
LOGGING
NOPARALLEL;


ALTER TABLE IBISTEMP ADD (
  CONSTRAINT PK_IBISTEMP
 PRIMARY KEY
 (TKEY));

---------------------------------------------------
--   CREATE TABLE IBISLOCK
---------------------------------------------------

CREATE TABLE IBISLOCK
(
  OBJECTID		VARCHAR2(100 CHAR),
  TYPE			CHAR(1 CHAR),
  HOST			VARCHAR2(100 CHAR),
  CREATIONDATE	TIMESTAMP(6),
  EXPIRYDATE	TIMESTAMP(6)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX PK_IBISLOCK ON IBISLOCK
(OBJECTID)
LOGGING
NOPARALLEL;


CREATE INDEX IX_IBISLOCK ON IBISLOCK
(EXPIRYDATE)
LOGGING
NOPARALLEL;


ALTER TABLE IBISLOCK ADD (
  CONSTRAINT PK_IBISLOCK
 PRIMARY KEY
 (OBJECTID));

--------------------------------------------------------
--  CREATE SEQUENCE SEQ_IBISSTORE
--------------------------------------------------------

CREATE SEQUENCE SEQ_IBISSTORE
  START WITH 12345
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
--------------------------------------------------------
--  CREATE SEQUENCE SEQ_IBISDATA
--------------------------------------------------------

CREATE SEQUENCE SEQ_IBISDATA
  START WITH 34567
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

--------------------------------------------------------
--  CREATE SEQUENCE SEQ_IBISTEMP
--------------------------------------------------------

CREATE SEQUENCE SEQ_IBISTEMP
  START WITH 56789
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

commit;
exit