<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
	<wsdl:types>
		<xs:schema targetNamespace="http://targetNamespace" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
			<xs:element name="Request">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Test" minOccurs="1">
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:minInclusive value="1"/>
									<xs:maxInclusive value="999"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:schema>
	</wsdl:types>
</wsdl:definitions>