name: Angular Vitest Tests

on:
  push:
    paths:
      - 'console/frontend/**'
      - '.github/workflows/angular-vitest-tests.yml'
    branches:
      - master
      - '[0-9]+.[0-9]+-release'
      - 'release/[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - '[0-9]+.[0-9]+-release'
      - 'release/[0-9]+.[0-9]+'

jobs:
  run-karma-tests:
    name: Vitest Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: console/frontend/src/main/frontend/
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Set timezone
      run: sudo timedatectl set-timezone Europe/Amsterdam

    - name: Install pnpm
      uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
      with:
        version: 11.25.0

    - name: Set up Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version: 24.19.0
        cache: pnpm
        cache-dependency-path: '**/pnpm-lock.yaml'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --ignore-scripts

    - name: Run Vitest tests
      run: pnpm test:ci
