name: Angular Karma Tests

on:
  push:
    paths:
      - 'console/frontend/**'
      - '.github/workflows/angular-karma-tests.yml'
    branches:
      - master
      - '[0-9]+.[0-9]+-release'
      - 'release/[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - '[0-9]+.[0-9]+-release'
      - 'release/[0-9]+.[0-9]+'

jobs:
  run-karma-tests:
    name: Karma Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: console/frontend/src/main/frontend/
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Set timezone
      run: sudo timedatectl set-timezone Europe/Amsterdam

    - name: Install pnpm
      uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
      with:
        version: 10.28.2

    - name: Set up Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: 24.15.0
        cache: pnpm
        cache-dependency-path: '**/pnpm-lock.yaml'

    - name: Install dependencies
      run: pnpm install

    - name: Run Karma tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
