name: Angular Vitest Tests

on:
  push:
    paths:
      - 'console/frontend/**'
      - '.github/workflows/angular-vitest-tests.yml'
    branches:
      - master
      - '[0-9]+.[0-9]+-release'
      - 'release/[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - '[0-9]+.[0-9]+-release'
      - 'release/[0-9]+.[0-9]+'

jobs:
  run-karma-tests:
    name: Vitest Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: console/frontend/src/main/frontend/
    steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

    - name: Set timezone
      run: sudo timedatectl set-timezone Europe/Amsterdam

    - name: Install pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
      with:
        version: 10.28.2

    - name: Set up Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: 24.16.0
        cache: pnpm
        cache-dependency-path: '**/pnpm-lock.yaml'

    - name: Install dependencies
      run: pnpm install

    - name: Run Vitest tests
      run: pnpm test:ci
