name: SonarQube Analyze

env:
  JDK_VERSION: 25

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+-release'
      - 'release/[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - '[0-9]+.[0-9]+-release'
      - 'release/[0-9]+.[0-9]+'

jobs:
  build:
    if: github.actor != 'renovate[bot]' && github.actor != 'dependabot[bot]'
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Required for SonarCloud
          fetch-depth: 0

      - name: Restore Sonar Cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            ~/.sonar/cache
          key: sonar-cache-${{ github.base_ref }}
          restore-keys: |
            sonar-cache-refs/heads/master
            sonar-cache-

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JDK_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          version: 10.28.2

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 24.14.0
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Save Sonar Cache
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        if: |
          always() &&
          (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/heads/[0-9]+.[0-9]+-release'))
        with:
          path: |
            ~/.sonar/cache
          key: sonar-cache-${{ github.base_ref }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
